services:
  app:
    image: nestjs-freelance-be
    container_name: nestjs-freelance-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - PORT=3000
      - IS_DEBUG=true
      - TYPEORM_DEBUG=true
      - BASE_URL=http://localhost:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_freelance
      - JWT_SECRET=nx2Hb3PaSHAPVmyEdvznZCQ5aSaq4IUH
    depends_on:
      - postgres
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_freelance
    ports:
      - '5433:5432'
    volumes:
      - nestjs-freelance-postgres:/var/lib/postgresql/data

volumes:
  nestjs-freelance-postgres:
