services:
  app:
    image: nestjs-freelance-be-dev
    container_name: nestjs-freelance-be-dev
    env_file: .env.dev
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbit
      - redis
    volumes:
      - ..:/app
      - /app/node_modules
    networks:
      - app
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:17
    container_name: nestjs-freelance-postgres-dev
    env_file: .env.dev
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  rabbit:
    image: rabbitmq:4.1-rc-management
    container_name: nestjs-freelance-rabbit-dev
    env_file: .env.dev
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - rabbitmq:/var/log/rabbitmq
    networks:
      - rabbitmq

  redis:
    image: redis:7
    container_name: nestjs-freelance-redis-dev
    env_file: .env.dev
    restart: always
    volumes:
      - redis:/data
    networks:
      - redis

networks:
  app:
  postgres:
  redis:
  rabbitmq:

volumes:
  postgres:
  rabbitmq:
  redis:
